// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type App struct {
	Package           string
	MetaAdded         int64
	MetaLastUpdated   int64
	MetaSourceCode    string
	LastSaveTriggered int64
}

type Task struct {
	ID                int64
	SaveRequestStatus sql.NullString
	SaveTaskStatus    sql.NullString
	SnapshotSwhid     sql.NullString
	HeadRevision      sql.NullString
	HeadRevisionDate  sql.NullString
}
